export const home_sample_data = [
  {
    id: 1,
    asset_code: 'LA100002',
    asset_name: 'Laptop HP Probook 450 G1',
    asset_category: 'Laptop',
    assigned_date: '10/04/2019',
    state: 'Accepted',
  },
  {
    id: 2,
    asset_code: 'LA100003',
    asset_name: 'Laptop HP Probook 450 G1',
    asset_category: 'Laptop',
    assigned_date: '10/04/2019',
    state: 'Accepted',
  },
  {
    id: 3,
    asset_code: 'MO00004',
    asset_name: 'Monitor Dell UltraSharp',
    asset_category: 'Monitor',
    assigned_date: '20/03/2021',
    state: 'Waiting for acceptance',
  },
  {
    id: 4,
    asset_code: 'MO00004',
    asset_name: 'Monitor Dell UltraSharp',
    asset_category: 'Monitor',
    assigned_date: '20/03/2021',
    state: 'Waiting for acceptance',
  },
  {
    id: 5,
    asset_code: 'MO00004',
    asset_name: 'Monitor Dell UltraSharp',
    asset_category: 'Monitor',
    assigned_date: '20/03/2021',
    state: 'Waiting for acceptance',
  },
  {
    id: 6,
    asset_code: 'MO00004',
    asset_name: 'Monitor Dell UltraSharp',
    asset_category: 'Monitor',
    assigned_date: '20/03/2021',
    state: 'Waiting for acceptance',
  },
  {
    id: 7,
    asset_code: 'MO00004',
    asset_name: 'Monitor Dell UltraSharp',
    asset_category: 'Monitor',
    assigned_date: '20/03/2021',
    state: 'Waiting for acceptance',
  },
  {
    id: 8,
    asset_code: 'MO00004',
    asset_name: 'Monitor Dell UltraSharp',
    asset_category: 'Monitor',
    assigned_date: '20/03/2021',
    state: 'Waiting for acceptance',
  },
  {
    id: 9,
    asset_code: 'MO00004',
    asset_name: 'Monitor Dell UltraSharp',
    asset_category: 'Monitor',
    assigned_date: '20/03/2021',
    state: 'Waiting for acceptance',
  },
  {
    id: 10,
    asset_code: 'MO00004',
    asset_name: 'Monitor Dell UltraSharp',
    asset_category: 'Monitor',
    assigned_date: '20/03/2021',
    state: 'Waiting for acceptance',
  },
  {
    id: 11,
    asset_code: 'MO00004',
    asset_name: 'Monitor Dell UltraSharp',
    asset_category: 'Monitor',
    assigned_date: '20/03/2021',
    state: 'Waiting for acceptance',
  },
  {
    id: 12,
    asset_code: 'MO00004',
    asset_name: 'Monitor Dell UltraSharp',
    asset_category: 'Monitor',
    assigned_date: '20/03/2021',
    state: 'Waiting for acceptance',
  },
  {
    id: 13,
    asset_code: 'MO00004',
    asset_name: 'Monitor Dell UltraSharp',
    asset_category: 'Monitor',
    assigned_date: '20/03/2021',
    state: 'Waiting for acceptance',
  },
  {
    id: 14,
    asset_code: 'MO00004',
    asset_name: 'Monitor Dell UltraSharp',
    asset_category: 'Monitor',
    assigned_date: '20/03/2021',
    state: 'Waiting for acceptance',
  },
  {
    id: 15,
    asset_code: 'MO00004',
    asset_name: 'Monitor Dell UltraSharp',
    asset_category: 'Monitor',
    assigned_date: '20/03/2021',
    state: 'Waiting for acceptance',
  },
  {
    id: 16,
    asset_code: 'MO00004',
    asset_name: 'Monitor Dell UltraSharp',
    asset_category: 'Monitor',
    assigned_date: '20/03/2021',
    state: 'Waiting for acceptance',
  },
  {
    id: 17,
    asset_code: 'MO00004',
    asset_name: 'Monitor Dell UltraSharp',
    asset_category: 'Monitor',
    assigned_date: '20/03/2021',
    state: 'Waiting for acceptance',
  },
  {
    id: 18,
    asset_code: 'MO00004',
    asset_name: 'Monitor Dell UltraSharp',
    asset_category: 'Monitor',
    assigned_date: '20/03/2021',
    state: 'Waiting for acceptance',
  },
];
